name: Build raspberry Image

on: [workflow_dispatch]

jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Update apt
      run: sudo apt-get update -qq
      
    - name: Install packer and qemu-user-static
      run: sudo apt-get install -y packer qemu-user-static

    - name: Set up Go 1.16
      uses: actions/setup-go@v1
      with:
        go-version: 1.16
      id: go

    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
      
    - name: CHeckout https://github.com/mkaczanowski/packer-builder-arm
      run: git clone https://github.com/mkaczanowski/packer-builder-arm
      
    - name: Switch to packer-build-arm directory
      run: cd packer-builder-arm
      
    - name: Checkout pwd
      run: pwd
      
    - name: Get to dependencies
      run: cd packer-builder-arm && go mod download
      
    - name: Go build
      run: cd packer-build-arm && go build
      
    - name: Create raspberry image
      run: sudo packer build packer-build-arm/boards/raspberry-pi/raspbian.json
